



tables = {
        "Daily Cash Movement": {
            "table": "cash_movement",
            "extension": ".csv",
            "account_index": [
                "Client",
                "Account Type",
                "Account"
            ],
            "column_names": [
                "date",
                "account_treecap",
                "portfolio_manager",
                "valueDate",
                "client",
                "clientName",
                "accountType",
                "account",
                "accountName",
                "subAccount",
                "subAccountName",
                "currency",
                "cashTitle",
                "journalGroup",
                "cashAmount",
                "instrumentType",
                "clientCurrency",
                "conversionRate",
                "journalAccountDesc",
                "cashMovementComment",
                "manuaLindicator",
                "journalAccountCode",
                "exchange",
                "symbol",
                "description",
                "strikePrice",
                "expiryDates",
                "putCall",
                "externalAccount",
                "ISIN",
                "exchangeTrade",
                "nostroAccount",
                "firstDelivery",
                "lastDelivery",
                "finalSettlementDate",
                "contractYear",
                "contractsize"
            ]
        },
        "Daily TRXs": {
            "table": "daily_transaction",
            "extension": ".csv",
            "account_index": [
                "Client",
                "Account Type",
                "Account"
            ],
            "abn_index": [
                "Symbol",
                "Expiry Date",
                "Put Call",
                "Strike Price",
                "Valuation Price Currency"
            ],
            "column_names": [
                "date",
                "account_treecap",
                "portfolio_manager",
                "category",
                "deal",
                "symbol_treecap",
                "abn_symbol",
                "client",
                "clientname",
                "accounttype",
                "account",
                "accountname",
                "subaccount",
                "subaccountname",
                "tradedate",
                "transref",
                "exchange",
                "transactioncurrency",
                "symbol",
                "description",
                "strikeprice",
                "expirydate",
                "isin",
                "ulvisin",
                "productgroup",
                "putcall",
                "transactiontype",
                "movementtype",
                "openclose",
                "buysell",
                "quantitylong",
                "quantityshort",
                "tradeprice",
                "grossconsideration",
                "grossconsiderationcurrency",
                "externalfees",
                "externalfeescurrency",
                "clearingfees",
                "clearingfeescurrency",
                "externalmemberid",
                "externalaccount",
                "counterparty",
                "clientcurrency",
                "conversionrate",
                "tradingunit",
                "settlementdate",
                "valuationprice",
                "valuationpricecurrency",
                "valuationdate",
                "giveupbroker",
                "giveuptakeup",
                "promptdate",
                "firstnoticedate",
                "lastnoticedate",
                "firstdeliverydate",
                "lastdeliverydate",
                "contractyearmonth",
                "strategycode",
                "contractsize",
                "exchangereference1",
                "exchangereference2",
                "exchangereference3",
                "relatedtransactiondate",
                "relatedreferencenumber",
                "relatedtransactiontype",
                "spotrefprice",
                "settlementprice",
                "spotreferencesettlement",
                "expirymarketsettlement",
                "unitofmeasurement",
                "tradetime",
                "matchingtimestampadditional",
                "externaltradeid",
                "exchangetradeid",
                "externalnumber",
                "ordernumber",
                "ticketnumber",
                "traderinitials",
                "comment",
                "safekeepingid",
                "placeofsafekeepingid",
                "couponinterestvalue",
                "couponinterestvaluecur",
                "pricingunit",
                "finalsettlementdate",
                "miccode",
                "contractualsettlementdate",
                "counterpartybroker",
                "poolref",
                "settlementinstructionreference",
                "TUI",
                "lasttradedate",
                "cob_lasttradedate",
                "FeeTransactionType"
            ]
        },
        "Dividends": {
            "table": "dividend_synthetics",
            "extension": ".csv",
            "account_index": [
                "Fund",
                "Strategy"
            ],
            "column_names": [
                "date",
                "account_treecap",
                "portfolio_manager",
                "ClientName",
                "Fund",
                "Swap",
                "Security",
                "RIC",
                "Type",
                "CashflowType",
                "UnderlyingCcy",
                "SwapCcy",
                "DivCashflowCcy",
                "Quantity",
                "DividendRate",
                "DividendPassthrough",
                "DividendAmountDivCcy",
                "PaymentCcy",
                "FXRate",
                "FXStatus",
                "DividendAmountPayCcy",
                "ExDate",
                "TradeID",
                "DividendPaymentDate",
                "SwapPaymentDate",
                "Country",
                "Region",
                "BBGTicker",
                "SEDOL",
                "ISIN",
                "PrefListingID",
                "TotalSettlement_ValueDC"
            ]
        },
        "Trade-0000006372": {
            "table": "trade_synthetics",
            "extension": ".csv",
            "account_index": [
                "Fund",
                "Strategy"
            ],
            "abn_index": [
                "RIC",
                "Trade Ccy"
            ],
            "column_names": [
                "date",
                "account_treecap",
                "portfolio_manager",
                "category",
                "deal",
                "symbol_treecap",
                "abn_symbol",
                "ClientName",
                "Fund",
                "Swap",
                "Strategy",
                "Security",
                "RIC",
                "Type",
                "TradeStatus",
                "TradeID",
                "Side",
                "TradeType",
                "TradeDate",
                "SettlementDate",
                "TradeCcy",
                "SwapCcy",
                "Quantity",
                "UnwindQuantity",
                "GrossPrice",
                "TradePrice",
                "FXRate",
                "NetPrice_SwapCcy",
                "GrossCloseNotional",
                "NetCloseNotional_SwapCcy",
                "TradedNotional_SwapCcy",
                "Spread",
                "BorrowCost",
                "DividendRate",
                "Commission",
                "Fees",
                "UnwindMethodology",
                "BenchmarkName",
                "NextReset",
                "NextResetPD",
                "Country",
                "Region",
                "PrefListingID",
                "Bloomberg",
                "SEDOL",
                "ISIN",
                "TradeVersion",
                "IndependentAmountComputationMode",
                "IndependentAmountPercentage",
                "IndependentAmount_SwapCcy",
                "UTI"
            ]
        },
        "TRX (L)": {
            "table": "trx",
            "extension": ".csv",
            "account_index": [
                "accountid"
            ],
            "column_names": [
                "BCCId",
                "account_treecap",
                "portfolio_manager",
                "clientid",
                "accountid",
                "clientname",
                "movementtype",
                "movementcode",
                "date",
                "oppositepartycode",
                "cashdescription",
                "journalAccount",
                "product_listingexchange",
                "productgroupcode",
                "productgroupname",
                "product_type",
                "product_symbol",
                "product_expiry",
                "product_strike",
                "product_instrumentidtype",
                "product_instrumentidvalue",
                "settlementtype",
                "exercisetype",
                "futurestyleindication",
                "ULV_ProductGroupCode",
                "ULV_ListingExchange",
                "ULV_Symbol",
                "ULV_Expiry",
                "ULV_PreferredTradingExchange",
                "ULV_InstrumentIDType",
                "ULV_InstrumentIDValue",
                "ULV_SafeKeepingId",
                "safeKeeping_safeKeepingid",
                "placeofsafekeepingid",
                "externalmember",
                "externalaccount",
                "exchange_preferredtradingexchange",
                "buysellcode",
                "openclosecode",
                "transactiontype",
                "quantitylong",
                "quantityshort",
                "primaryamount",
                "primaryamountdc",
                "primaryamountcurrency_currencycode",
                "primaryamountcurrency_currencypricingunit",
                "settlementprice",
                "settlementpricecurrency_currencycode",
                "settlementpricecurrency_currencypricingunit",
                "businessdate",
                "transactiondate",
                "settlementdate",
                "transactionprice",
                "transactionpricefractional",
                "transactionPricecurrency_currencycode",
                "transactionPricecurrency_currencypricingunit",
                "transactioncurrency",
                "centralcounterpartyid",
                "comment",
                "conversionfactor",
                "externalnumber",
                "exectraderid",
                "internalreference",
                "internalunsettledreference",
                "journalentryamount_value",
                "journalentryamount_valuedc",
                "journalentryamount_valuecur",
                "grossindicator",
                "fromtransaction",
                "fromtransactionreference",
                "fromtransactiondate",
                "tradereference",
                "poolref",
                "ordernumber",
                "ticketnumber",
                "timestamp",
                "traderinitials",
                "tradingunit",
                "transactionorigin",
                "transactiontypecode",
                "conversiontradingunit",
                "deliveredtradingunit",
                "valuedate",
                "contractsize",
                "rof_depot",
                "rof_settlementdate",
                "rof_settlementprice",
                "rof_quantity",
                "rof_transactiondate",
                "rof_transactionreference",
                "brokerfee_value",
                "brokerfee_valuedc",
                "brokerfee_valuecur",
                "clearingfee_value",
                "clearingfee_valuedc",
                "clearingfeecur",
                "commission_value",
                "commission_valuedc",
                "commission_valuecur",
                "exchangefee_value",
                "exchangefee_valuedc",
                "exchangefee_valuecur",
                "effectivevalue_value",
                "effectivevaluedc",
                "effectivevalue_valuecur",
                "stampduty_value",
                "stampduty_valuedc",
                "stampduty_valuecur",
                "totalpremium_value",
                "totalpremiumvaluedc",
                "totalpremium_valuecur",
                "totalsettlementvalue",
                "totalsettlement_valuedc",
                "totalsettlement_valuecur",
                "exttransidclearing",
                "exttransidexchange",
                "couponinterest_value",
                "couponinterest_valuedc",
                "couponinterest_valuetcur",
                "adjustment_value",
                "adjustment_valuedc",
                "adjustment_valuecur",
                "countervalue_value",
                "countervalue_valuedc",
                "countervalue_valuecur",
                "settlementbalance_value",
                "settlementbalance_valuedc",
                "settlementbalance_valuecur",
                "transactionlevy_value",
                "transactionlevy_valuedc",
                "transactionlevy_valuecur",
                "givetakeupindicator",
                "preferredtradingexchange",
                "giveupbroker",
                "counterpartybroker",
                "matchingtradetimestamp",
                "exchangereference1",
                "exchangereference2",
                "exchangereference3",
                "tradercardreference",
                "orderidnew",
                "externalpositionaccount",
                "LiquidityCode",
                "Journal_Group",
                "Journal_Account_Description",
                "Manual_Indicator",
                "MICCode",
                "SettlementInstructionReference",
                "TUI"
            ]
        },
        "3182-C3182-CSV Interest Account Level": {
            "table": "interest_account",
            "extension": ".csv",
            "account_index": [
                "Client",
                "Account Type",
                "Account"
            ],
            "column_names": [
                "date",
                "account_treecap",
                "portfolio_manager",
                "BCCId",
                "Holding",
                "Client",
                "Client_Name",
                "Account_Type",
                "Account",
                "Account_Name",
                "OppositeParty_OppositePartyCode",
                "InterestCalculationStatus",
                "InterestType",
                "ValueDate",
                "GrossBalanceAmount_Value",
                "GrossBalanceAmount_ValueDC",
                "GrossBalanceAmount_ValueCur",
                "DaysAccrued",
                "InterestRateDebit",
                "InterestRateCredit",
                "BasicInterestRateDebit",
                "BasicInterestRateCredit",
                "CommercialRiseDebit",
                "CommercialRiseCredit",
                "LiquiditySpread",
                "MinimumRate",
                "InterestAmount",
                "InterestAmountDC",
                "InterestAmountCur",
                "Product_ListingExchange",
                "Product_ProductGroupCode",
                "Product_ProductGroupName",
                "Product_Symbol",
                "Product_Expiry",
                "Product_InstrumentIDType",
                "Product_InstrumentIDValue",
                "Product_ShortName",
                "Depot_DepotId",
                "SafeKeeping_SafeKeepingId",
                "QuantityShort",
                "ShortStockPrice",
                "MarkToMarketAmount",
                "MarkToMarketAmountDC",
                "MarktomarketAmountCur",
                "FixedDealIndicator",
                "Bookedto_Client",
                "Bookedto_Accounttype",
                "Bookedto_AccountNumber",
                "Bookedto_SubaccountNumber"
                ]
        },
        "Daily Loan Rate": {
            "table": "daily_loan_rate",
            "extension": ".csv",
            "account_index": [
                "MICS Client Number"
            ],
            "column_names": [
                "date",
                "account_treecap",
                "portfolio_manager",
                "grip_client_number",
                "mics_client_number",
                "identification_type",
                "identification",
                "product_short_name",
                "position_long",
                "position_short",
                "depot",
                "safekeeping",
                "interestrate"
            ],
            "date": "date"
        },


}


